package com.example.localization

enum class AppLanguage(val code: String, val displayName: String, val flag: String) {
    ENGLISH("en", "English", "🌐"),
    TAMIL("ta", "தமிழ்", "🌐"),
    TANGLISH("ta-en", "Tanglish", "🌐")
}

object StringsLocalization {

    fun get(key: String, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.ENGLISH -> englishMap[key] ?: key
            AppLanguage.TAMIL -> tamilMap[key] ?: englishMap[key] ?: key
            AppLanguage.TANGLISH -> tanglishMap[key] ?: englishMap[key] ?: key
        }
    }

    private val englishMap = mapOf(
        "app_title" to "HOMEo AI",
        "app_tagline" to "Smart Clinic. Better Care.",
        "book_appointment" to "Book Appointment",
        "call_clinic" to "Call Clinic",
        "get_directions" to "Get Directions",
        "contact_clinic" to "Contact Clinic",
        "login" to "Login",
        "register" to "Register",
        "patient_portal" to "Patient Portal",
        "clinic_staff_portal" to "Doctor / Staff Portal",
        "switch_to_clinic" to "Doctor Portal",
        "switch_to_patient" to "Patient View",
        "our_doctors" to "Our Classical Homeopaths",
        "services_offered" to "Specialized Healing Services",
        "working_hours" to "Clinic Timings",
        "consultation_fee" to "Consultation Fee",
        "experience" to "years experience",
        "qualification" to "Qualification",
        "specialization" to "Specialization",
        "facilities" to "Clinic Amenities",
        "emergency_contact" to "Emergency Helpline",
        "address" to "Clinic Address",

        // Booking Flow
        "step_1_doctor" to "1. Select Doctor",
        "step_2_date" to "2. Select Date",
        "step_3_time" to "3. Select Time",
        "step_4_details" to "4. Patient Details",
        "step_5_confirm" to "5. Confirm Booking",
        "choose_doctor" to "Choose Doctor",
        "choose_date" to "Choose Date",
        "choose_time" to "Choose Time Slot",
        "available_slots" to "Available Appointment Slots",
        "no_slots_available" to "No slots available for this day. Doctor may be unavailable or slots are fully booked.",
        "patient_name" to "Full Name",
        "patient_phone" to "Mobile Number",
        "patient_age" to "Age",
        "patient_gender" to "Gender",
        "male" to "Male",
        "female" to "Female",
        "other" to "Other",
        "reason_for_visit" to "Chief Complaints / Reason for Visit",
        "consultation_type" to "Consultation Type",
        "in_clinic" to "In-Clinic Visit",
        "online_tele" to "Online Video Consultation",
        "payment_method" to "Payment Method",
        "pay_at_clinic" to "Pay at Clinic (Reception)",
        "pay_online" to "Pay Online (UPI / Card / NetBanking)",
        "confirm_booking_button" to "CONFIRM BOOKING",
        "booking_in_progress" to "Reserving your appointment slot...",
        "slot_taken_error" to "Sorry, this slot was just booked. Please select another time.",

        // Confirmation
        "appointment_confirmed" to "Appointment Confirmed",
        "appointment_id" to "Appointment ID",
        "add_to_calendar" to "Add to Calendar",
        "view_appointment" to "View Appointment",
        "reschedule" to "Reschedule",
        "cancel" to "Cancel",
        "doctor" to "Doctor",
        "clinic" to "Clinic",
        "date" to "Date",
        "time" to "Time",
        "status" to "Status",
        "qr_scan_note" to "Show this QR code at clinic reception for fast instant token check-in",

        // Queue
        "live_queue" to "Live Queue Status",
        "your_token" to "Your Token",
        "now_serving" to "Now Serving",
        "patients_ahead" to "Patients Ahead",
        "estimated_wait" to "Estimated Waiting Time",
        "check_in" to "Check In",
        "check_in_success" to "Checked in successfully! Your Token has been assigned.",

        // Dashboard Tabs
        "my_appointments" to "My Appointments",
        "upcoming" to "Upcoming",
        "completed" to "Completed",
        "cancelled" to "Cancelled",
        "notifications" to "Notifications",
        "profile" to "My Profile",

        // Clinic Staff Portal
        "today_appointments" to "Today's Clinic Dashboard",
        "all" to "All",
        "confirmed" to "Confirmed",
        "waiting" to "Waiting",
        "in_consultation" to "In Consultation",
        "no_show" to "No-Show",
        "start_consultation" to "Start Consultation",
        "complete_consultation" to "Complete",
        "call_next" to "Call Next Patient",
        "medicine_inventory" to "Pharmacy Inventory",
        "stock" to "Stock",
        "analytics" to "Clinic Analytics",
        "revenue" to "Revenue",
        "settings" to "Clinic Settings & Integrations",

        // AI Assistant
        "ai_assistant_title" to "HOMEo AI Voice & Booking Assistant",
        "ai_assistant_subtitle" to "Speak in English, Tamil, or Tanglish to book or query",
        "tap_to_speak" to "Tap microphone to speak",
        "listening" to "Listening...",
        "ask_sample_1" to "Innaikku evening doctor appointment venum",
        "ask_sample_2" to "Book an appointment with Dr. Rajesh for tomorrow",
        "ask_sample_3" to "டாக்டர் அப்பாய்ன்ட்மென்ட் புக் பண்ணனும்"
    )

    private val tamilMap = mapOf(
        "app_title" to "HOMEo AI",
        "app_tagline" to "ஸ்மார்ட் கிளினிக். சிறந்த சிகிச்சை.",
        "book_appointment" to "முன்பதிவு செய்யவும்",
        "call_clinic" to "கிளினிக்கை அழைக்க",
        "get_directions" to "வழித்தடம் பார்க்க",
        "contact_clinic" to "தொடர்பு கொள்ள",
        "login" to "உள்நுழைக",
        "register" to "பதிவு செய்க",
        "patient_portal" to "நோயாளி தளம்",
        "clinic_staff_portal" to "மருத்துவர் / ஊழியர் தளம்",
        "switch_to_clinic" to "மருத்துவர் தளம்",
        "switch_to_patient" to "நோயாளி பார்வை",
        "our_doctors" to "எங்கள் ஹோமியோபதி மருத்துவர்கள்",
        "services_offered" to "சிகிச்சை சேவைகள்",
        "working_hours" to "கிளினிக் வேலை நேரம்",
        "consultation_fee" to "ஆலோசனை கட்டணம்",
        "experience" to "ஆண்டுகள் அனுபவம்",
        "qualification" to "கல்வி தகுதி",
        "specialization" to "சிறப்பு துறை",
        "facilities" to "கிளினிக் வசதிகள்",
        "emergency_contact" to "அவசர உதவி",
        "address" to "கிளினிக் முகவரி",

        // Booking Flow
        "step_1_doctor" to "1. மருத்துவரை தேர்வு செய்க",
        "step_2_date" to "2. தேதியை தேர்வு செய்க",
        "step_3_time" to "3. நேரத்தை தேர்வு செய்க",
        "step_4_details" to "4. நோயாளி விவரங்கள்",
        "step_5_confirm" to "5. உறுதிப்படுத்துதல்",
        "choose_doctor" to "மருத்துவரை தேர்வு செய்யவும்",
        "choose_date" to "தேதியை தேர்வு செய்யவும்",
        "choose_time" to "நேர இடைவெளியை தேர்வு செய்க",
        "available_slots" to "கிடைக்கும் நேரங்கள்",
        "no_slots_available" to "இந்த தேதியில் முன்பதிவு செய்ய நேரங்கள் இல்லை.",
        "patient_name" to "முழு பெயர்",
        "patient_phone" to "மொபைல் எண்",
        "patient_age" to "வயது",
        "patient_gender" to "பாலினம்",
        "male" to "ஆண்",
        "female" to "பெண்",
        "other" to "மற்றவை",
        "reason_for_visit" to "சிகிச்சைக்கு காரணம் / குறிகுறி",
        "consultation_type" to "சந்திப்பு முறை",
        "in_clinic" to "நேரடி கிளினிக் வருகை",
        "online_tele" to "ஆன்லைன் வீடியோ சந்திப்பு",
        "payment_method" to "கட்டண முறை",
        "pay_at_clinic" to "கிளினிக்கில் செலுத்தவும்",
        "pay_online" to "ஆன்லைனில் செலுத்தவும் (UPI/Card)",
        "confirm_booking_button" to "முன்பதிவை உறுதி செய்",
        "booking_in_progress" to "முன்பதிவு செய்யப்படுகிறது...",
        "slot_taken_error" to "மன்னிக்கவும், இந்த நேரம் முன்பதிவு செய்யப்பட்டுவிட்டது. வேறு நேரத்தை தேர்வு செய்க.",

        // Confirmation
        "appointment_confirmed" to "சந்திப்பு உறுதி செய்யப்பட்டது",
        "appointment_id" to "முன்பதிவு எண்",
        "add_to_calendar" to "நாட்காட்டியில் சேர்க்க",
        "view_appointment" to "விவரங்களை பார்க்க",
        "reschedule" to "தேதி மாற்றுக",
        "cancel" to "ரத்து செய்க",
        "doctor" to "மருத்துவர்",
        "clinic" to "கிளினிக்",
        "date" to "தேதி",
        "time" to "நேரம்",
        "status" to "நிலை",
        "qr_scan_note" to "டோக்கன் பெற இந்த QR குறியீட்டை வரவேற்பறையில் காட்டவும்",

        // Queue
        "live_queue" to "நேரலை வரிசை நிலை",
        "your_token" to "உங்கள் டோக்கன்",
        "now_serving" to "இப்போது அழைக்கப்படுவது",
        "patients_ahead" to "முன்னால் உள்ளவர்கள்",
        "estimated_wait" to "தோராய காத்திருப்பு நேரம்",
        "check_in" to "செக்-இன் செய்க",
        "check_in_success" to "செக்-இன் முடிந்தது! டோக்கன் எண் ஒதுக்கப்பட்டது.",

        // Dashboard Tabs
        "my_appointments" to "எனது முன்பதிவுகள்",
        "upcoming" to "வரவிருக்கும்",
        "completed" to "முடிந்தவை",
        "cancelled" to "ரத்து செய்தவை",
        "notifications" to "அறிவிப்புகள்",
        "profile" to "என் சுயவிவரம்",

        // Clinic Staff Portal
        "today_appointments" to "இன்றைய கிளினிக் அட்டவணை",
        "all" to "அனைத்தும்",
        "confirmed" to "உறுதி செய்யப்பட்டவை",
        "waiting" to "காத்திருப்போர்",
        "in_consultation" to "சிகிச்சையில்",
        "no_show" to "வராதவர்கள்",
        "start_consultation" to "சிகிச்சையை தொடங்கு",
        "complete_consultation" to "முடிக்கவும்",
        "call_next" to "அடுத்த நோயாளியை அழை",
        "medicine_inventory" to "மருந்து கையிருப்பு",
        "stock" to "கையிருப்பு",
        "analytics" to "கிளினிக் பகுப்பாய்வு",
        "revenue" to "வருவாய்",
        "settings" to "அமைப்புகள் & இணைப்புகள்",

        // AI Assistant
        "ai_assistant_title" to "HOMEo AI குரல் முன்பதிவு உதவியாளர்",
        "ai_assistant_subtitle" to "தமிழ், ஆங்கிலம் அல்லது Tanglish-ல் பேசி முன்பதிவு செய்யலாம்",
        "tap_to_speak" to "பேச மைக்ரோஃபோனைத் தொடவும்",
        "listening" to "கேட்கிறது...",
        "ask_sample_1" to "இன்னைக்கு ஈவ்னிங் டாக்டர் அப்பாய்ன்ட்மென்ட் வேணும்",
        "ask_sample_2" to "நாளைக்கு டாக்டர் ராஜேஷ்க்கு புக் பண்ணு",
        "ask_sample_3" to "டாக்டர் ஆலோசனை கட்டணம் எவ்வளவு?"
    )

    private val tanglishMap = mapOf(
        "app_title" to "HOMEo AI",
        "app_tagline" to "Smart Clinic. Better Care.",
        "book_appointment" to "Appointment Book Pannu",
        "call_clinic" to "Clinic-ku Call Pannu",
        "get_directions" to "Directions Paaru",
        "contact_clinic" to "Contact Pannu",
        "login" to "Login",
        "register" to "Register",
        "patient_portal" to "Patient Portal",
        "clinic_staff_portal" to "Doctor / Staff Portal",
        "switch_to_clinic" to "Doctor Portal",
        "switch_to_patient" to "Patient View",
        "our_doctors" to "Namma Homeopathy Doctors",
        "services_offered" to "Treatments & Services",
        "working_hours" to "Clinic Timings",
        "consultation_fee" to "Doctor Fee",
        "experience" to "varusham experience",
        "qualification" to "Qualification",
        "specialization" to "Specialist",
        "facilities" to "Clinic Amenities",
        "emergency_contact" to "Emergency Helpline",
        "address" to "Clinic Address",

        // Booking Flow
        "step_1_doctor" to "1. Doctor Select Pannu",
        "step_2_date" to "2. Date Select Pannu",
        "step_3_time" to "3. Time Slot Select Pannu",
        "step_4_details" to "4. Patient Details",
        "step_5_confirm" to "5. Booking Confirm Pannu",
        "choose_doctor" to "Doctor-ah Select Pannunga",
        "choose_date" to "Date Select Pannunga",
        "choose_time" to "Time Slot Select Pannunga",
        "available_slots" to "Available Time Slots",
        "no_slots_available" to "Indha date-la slots illa. Vera date select pannunga.",
        "patient_name" to "Full Name",
        "patient_phone" to "Mobile Number",
        "patient_age" to "Age",
        "patient_gender" to "Gender",
        "male" to "Male",
        "female" to "Female",
        "other" to "Other",
        "reason_for_visit" to "Yenna Problem / Reason for Visit",
        "consultation_type" to "Consultation Type",
        "in_clinic" to "Direct-ah Clinic Varen",
        "online_tele" to "Online Video Consultation",
        "payment_method" to "Payment Method",
        "pay_at_clinic" to "Clinic-la Direct-ah Pay Panren",
        "pay_online" to "Online-la Pay Panren (UPI/GPay)",
        "confirm_booking_button" to "CONFIRM BOOKING",
        "booking_in_progress" to "Booking process aagudhu...",
        "slot_taken_error" to "Sorry, indha slot ippo dhan book aayiruchu. Vera slot choose pannunga.",

        // Confirmation
        "appointment_confirmed" to "Appointment Confirm Aayiduchu!",
        "appointment_id" to "Appointment ID",
        "add_to_calendar" to "Calendar-la Add Pannu",
        "view_appointment" to "Appointment Details Paaru",
        "reschedule" to "Date Maathu",
        "cancel" to "Cancel Pannu",
        "doctor" to "Doctor",
        "clinic" to "Clinic",
        "date" to "Date",
        "time" to "Time",
        "status" to "Status",
        "qr_scan_note" to "Reception-la token vaanga indha QR Code kaatunga",

        // Queue
        "live_queue" to "Live Queue Status",
        "your_token" to "Unga Token",
        "now_serving" to "Ippo Paakkaradhu",
        "patients_ahead" to "Munnadi Irukkuravanga",
        "estimated_wait" to "Waiting Time (Approx)",
        "check_in" to "Check-in Pannu",
        "check_in_success" to "Check-in aayiduchu! Unga Token number ready.",

        // Dashboard Tabs
        "my_appointments" to "Ennoda Appointments",
        "upcoming" to "Upcoming",
        "completed" to "Mudinjadhu",
        "cancelled" to "Cancel Aaanadhu",
        "notifications" to "Notifications",
        "profile" to "My Profile",

        // Clinic Staff Portal
        "today_appointments" to "Innaikku Clinic Dashboard",
        "all" to "Ellaam",
        "confirmed" to "Confirmed",
        "waiting" to "Waiting List",
        "in_consultation" to "Doctor Kitta",
        "no_show" to "Varaadha aalunga",
        "start_consultation" to "Consultation Start",
        "complete_consultation" to "Complete",
        "call_next" to "Next Patient Call Pannu",
        "medicine_inventory" to "Homeo Medicines Stock",
        "stock" to "Stock",
        "analytics" to "Clinic Analytics",
        "revenue" to "Revenue",
        "settings" to "Settings & Integrations",

        // AI Assistant
        "ai_assistant_title" to "HOMEo AI Voice Booking Assistant",
        "ai_assistant_subtitle" to "Tanglish, Tamil, English-la pesi book pannalaam",
        "tap_to_speak" to "Mic click panni pesunga",
        "listening" to "Listen pannudhu...",
        "ask_sample_1" to "Innaikku evening doctor appointment venum",
        "ask_sample_2" to "Naalaikku Dr. Rajesh ku book pannu",
        "ask_sample_3" to "Doctor fee evalavu?"
    )
}
